### ISSUE TITLE
perdon, como se compila esto?

### ISSUE THREAD

**Issue by icarito** [HuayraLinux/elantech-marble-dkms#1]

**Comment by matiasdelellis** [comment]
Hola,
Si lo queres compilar para Huayra espera que ni bien podamos subimos el paquete oficial, y luego de instalarlo solo necesitarias reiniciar tu maquina.
Ahora encontramos otros bugs de este driver junto el kernel 3.16 y estamos haciendo algunas pruebas..

Saludos.

**Comment by matiasdelellis** [comment]
El driver ya se encuentra en Huayra 3.

> sudo apt-get install elantech-marble-dkms

Cualquier cosa escribinos..
Saludos!. :wink:
